<?php
/**
 * CategoryTreeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Taxonomy API
 *
 * Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CategoryTreeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CategoryTreeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fetchItemAspects
     *
     * Get Aspects for All Leaf Categories in a Marketplace.
     *
     */
    public function testFetchItemAspects()
    {
    }

    /**
     * Test case for getCategorySubtree
     *
     * Get a Category Subtree.
     *
     */
    public function testGetCategorySubtree()
    {
    }

    /**
     * Test case for getCategorySuggestions
     *
     * Get Suggested Categories.
     *
     */
    public function testGetCategorySuggestions()
    {
    }

    /**
     * Test case for getCategoryTree
     *
     * Get a Category Tree.
     *
     */
    public function testGetCategoryTree()
    {
    }

    /**
     * Test case for getCompatibilityProperties
     *
     * Get Compatibility Properties.
     *
     */
    public function testGetCompatibilityProperties()
    {
    }

    /**
     * Test case for getCompatibilityPropertyValues
     *
     * Get Compatibility Property Values.
     *
     */
    public function testGetCompatibilityPropertyValues()
    {
    }

    /**
     * Test case for getDefaultCategoryTreeId
     *
     * Get a Default Category Tree ID.
     *
     */
    public function testGetDefaultCategoryTreeId()
    {
    }

    /**
     * Test case for getItemAspectsForCategory
     *
     * .
     *
     */
    public function testGetItemAspectsForCategory()
    {
    }
}
